import os
p=Environment(COMPILATIONDB_USE_ABSPATH=True,CCFLAGS=['-Wall','-I../','-O2'],CXXFLAGS=['--std=c++11'],LIBS='Irrlicht')
p.AppendENVPath('PATH',os.environ.get('PATH'))
p.Tool('compilation_db')
p.CompilationDatabase()
ss=['p.cpp']
ml=p.Program('ml',ss)
