import os
import subprocess
import urllib.request
import shutil
p=Environment(COMPILATIONDB_USE_ABSPATH=True,CCFLAGS=['-Wall','-I../','-O2'],CXXFLAGS=['--std=c++20'],LIBS='pthread')
p.AppendENVPath('PATH',os.environ.get('PATH'))
p.Tool('compilation_db')
p.CompilationDatabase()
p.ParseConfig('pkg-config --cflags --libs sndfile')
ss=['m.cpp']
sksl=p.Program('sksl',ss)
